# Generated by Django 3.1 on 2021-12-08 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0006_auto_20211208_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='edited_by',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='article_edited_by', to='blog_app.writer'),
        ),
        migrations.AlterField(
            model_name='article',
            name='written_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article_written_by', to='blog_app.writer'),
        ),
    ]
