# Generated by Django 3.1 on 2021-12-08 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_auto_20211208_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_edited_by', to='blog_app.writer'),
        ),
        migrations.AlterField(
            model_name='article',
            name='written_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_written_by', to='blog_app.writer'),
        ),
    ]
